### ISSUE TITLE
怎么用啊可以写详细点吗没学过python就算配置了环境仍然显示 No module named 'requests'的错误

### ISSUE THREAD

**Issue by METALLICAa** [Cyrus97/HDU#1]
怎么用啊可以写详细点吗没学过python就算配置了环境仍然显示 No module named 'requests'的错误

**Comment by Cyrus97** [comment]
看看[README](https://github.com/Cyrus97/HDU#%E5%AE%89%E8%A3%85)，安装库 `pip install -r ./requirements.txt`

**Comment by METALLICAa** [comment]
能不能说下具体操作我看到readme的内容但是运行不了 百度给的命令符也不会用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cyrus"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月18日(星期四) 晚上10:15
收件人:&nbsp;"Cyrus97/HDU"<HDU@noreply.github.com&gt;;
抄送:&nbsp;"陶靖"<1172570159@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Cyrus97/HDU] 怎么用啊可以写详细点吗没学过python就算配置了环境仍然显示 No module named 'requests'的错误 (#1)





 
看看README，安装库 pip install -r ./requirements.txt

**Comment by Cyrus97** [comment]
请先确保已安装 Python 环境，并确保已安装 pip，然后再在项目根目录下运行 `pip install -r ./requirements.txt`。
